add vuepress plausible plugin
protocol/nft-website pull request #284
Opened 2022-11-28 18:17 UTC by cmunns

2022-11-28 18:18 UTC, filecorgi commented
- Image optimization came back clean!
- Vuepress build was successful!
- No markdown files were changed, so no page checks were run!

2022-12-01 22:33 UTC, drewdelano commented on docs/.vuepress/config.js
> +        md.use(require('markdown-it-image-lazy-loading'))
weird whitespace formatting?  maybe this is a tabs and spaces situation?

2022-12-01 22:34 UTC, drewdelano commented on package-lock.json
> +  "lockfileVersion": 2,
the lockfile change here feels pretty substantial

2022-12-02 15:49 UTC, filecorgi commented
- Image optimization came back clean!
- Vuepress build was successful!
- No markdown files were changed, so no page checks were run!

2023-01-20 15:45 UTC, filecorgi commented
- Image optimization came back clean!
- Vuepress build was successful!
- No markdown files were changed, so no page checks were run!

2023-01-20 16:20 UTC, filecorgi commented
- Image optimization came back clean!
- Vuepress build failed...

```

> nft-school@2.0.0 docs:build
> NODE_OPTIONS=--openssl-legacy-provider vuepress build docs

node: --openssl-legacy-provider is not allowed in NODE_OPTIONS
```
- No markdown files were changed, so no page checks were run!

2023-01-20 16:29 UTC, yusefnapora requested changes
Hmm, on second thought... the "filecorgi" CI script is still apparently running on node 16, which chokes with the `--openssl-legacy-provider` flag.

So maybe the thing to do here is try reverting back to node 16 and lockfile v1, so we have a consistent env everywhere. I'll try that and see if that sorts things out.

2023-01-20 16:36 UTC, filecorgi commented
- Image optimization came back clean!
- Vuepress build was successful!
- No markdown files were changed, so no page checks were run!

2023-01-20 16:42 UTC, yusefnapora commented
lol, okay. Fleek is dead set on using node 18, apparently, so I brought back the fixes and just made the CI script also use node 18. 🤞

2023-01-20 16:43 UTC, filecorgi commented
- Image optimization came back clean!
- Vuepress build was successful!
- No markdown files were changed, so no page checks were run!

2023-01-20 16:53 UTC, yusefnapora approved these changes
Okay, everything seems to be building again :) @cmunns feel free to merge if you're alright with the changes I made.

2023-01-23 15:31 UTC, merged